import Link from 'next/link';
export const metadata = { title: 'Privacy Policy | VEYRA' };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen pt-[70px] max-w-3xl mx-auto px-6 py-16">
      <div className="section-label">Legal</div>
      <h1 className="font-display text-4xl font-light mb-2">Privacy Policy</h1>
      <p className="text-muted text-sm mb-10">Last updated: January 1, 2026</p>
      {[
        { title: 'Information We Collect', content: 'We collect information you provide directly (name, email, phone, shipping address), information generated by your use of our platform (purchase history, browsing behavior, search queries, liked products), and technical information (device type, IP address, browser type). We do not sell your personal information to third parties.' },
        { title: 'How We Use Your Information', content: 'We use your information to: process orders and payments, personalize your shopping experience and AI recommendations, send order updates and notifications (with your consent), improve our platform and AI models, detect and prevent fraud, comply with legal obligations, and communicate with you about your account.' },
        { title: 'AI & Personalization', content: 'VEYRA uses AI to provide personalized product recommendations, style suggestions, and trend analysis. This involves processing your browsing history, purchase history, and saved items. You can opt out of personalization in Settings → Privacy.' },
        { title: 'Data Sharing', content: 'We share your information with: sellers (to fulfill your orders — only necessary details), payment processors (Paystack, Flutterwave — for payment processing), delivery partners (for order shipping), and legal authorities (when required by law). We never sell your data.' },
        { title: 'Data Security', content: 'We implement industry-standard security measures including encryption of data in transit and at rest, secure authentication with JWT tokens, role-based access controls, regular security audits, and protection against SQL injection and XSS attacks.' },
        { title: 'Cookies', content: 'We use essential cookies for authentication and security, functional cookies for cart and preferences, and analytics cookies to understand how users use our platform. You can control cookies through your browser settings, but some features may not work without essential cookies.' },
        { title: 'Your Rights', content: 'You have the right to access your personal data, correct inaccurate data, request deletion of your data, opt out of marketing communications, data portability (export your data), and withdraw consent. To exercise these rights, contact privacy@veyra.ng.' },
        { title: 'Data Retention', content: 'We retain your account data for as long as your account is active. After account deletion, we retain transaction records for 7 years for legal and tax purposes. Other data is deleted within 30 days of account closure.' },
        { title: "Children's Privacy", content: 'VEYRA is not intended for users under 18. We do not knowingly collect personal information from minors. If we discover we have collected data from a minor, we will delete it immediately.' },
        { title: 'Contact', content: 'For privacy concerns or data requests, contact our Data Protection Officer at privacy@veyra.ng or write to: Veyra Technologies Ltd, Data Protection, Lagos, Nigeria.' },
      ].map(s => (
        <div key={s.title} className="mb-8">
          <h2 className="text-base font-semibold mb-2 text-gold">{s.title}</h2>
          <p className="text-sm text-muted leading-relaxed">{s.content}</p>
        </div>
      ))}
      <div className="mt-12 pt-6 border-t border-white/07 flex gap-4 text-sm">
        <Link href="/terms" className="text-gold hover:text-gold-light">Terms & Conditions</Link>
        <Link href="/help" className="text-gold hover:text-gold-light">Help Center</Link>
      </div>
    </div>
  );
}
